---@class Fansi
---@field config FansiConfig
local Fansi = {}

---@alias Contrast "hard" | "soft" | ""

---@class ItalicConfig
---@field strings boolean
---@field comments boolean
---@field operators boolean
---@field folds boolean
---@field emphasis boolean

---@class HighlightDefinition
---@field ctermfg (number | string)?
---@field ctermbg (number | string)?
---@field sp string?
---@field blend integer?
---@field bold boolean?
---@field standout boolean?
---@field underline boolean?
---@field undercurl boolean?
---@field underdouble boolean?
---@field underdotted boolean?
---@field strikethrough boolean?
---@field italic boolean?
---@field reverse boolean?
---@field nocombine boolean?

---@class FansiConfig
---@field terminal_colors boolean?
---@field undercurl boolean?
---@field underline boolean?
---@field bold boolean?
---@field italic ItalicConfig?
---@field strikethrough boolean?
---@field contrast Contrast?
---@field invert_selection boolean?
---@field invert_signs boolean?
---@field invert_tabline boolean?
---@field invert_intend_guides boolean?
---@field inverse boolean?
---@field overrides table<string, HighlightDefinition>?
---@field palette_overrides table<string, string>?
Fansi.config = {
  terminal_colors = true,
  undercurl = true,
  underline = true,
  bold = true,
  italic = {
    strings = true,
    emphasis = true,
    comments = true,
    operators = false,
    folds = true,
  },
  strikethrough = true,
  invert_selection = false,
  invert_signs = false,
  invert_tabline = false,
  invert_intend_guides = false,
  inverse = true,
  contrast = "",
  palette_overrides = {},
  overrides = {},
  dim_inactive = false,
  transparent_mode = false,
}

Fansi.palette = {
  Black = 0,
  DarkRed = 1,
  DarkGreen = 2,
  DarkYellow = 3,
  DarkBlue = 4,
  DarkMagenta = 5,
  DarkCyan = 6,
  Gray = 7,
  BrightBlack = 8,
  Red = 9,
  Green = 10,
  Yellow = 11,
  Blue = 12,
  Magenta = 13,
  Cyan = 14,
  White = 15,
}

local function get_groups()
  local colors = {
    bg0 = Fansi.palette.Black,
    bg1 = Fansi.palette.Black,
    bg2 = Fansi.palette.Black,
    bg3 = Fansi.palette.BrightBlack,
    bg4 = Fansi.palette.BrightBlack,
    fg0 = Fansi.palette.White,
    fg1 = Fansi.palette.White,
    fg2 = Fansi.palette.Gray,
    fg3 = Fansi.palette.Gray,
    fg4 = Fansi.palette.Gray,
    red = Fansi.palette.Red,
    green = Fansi.palette.Green,
    yellow = Fansi.palette.Yellow,
    blue = Fansi.palette.Blue,
    magenta = Fansi.palette.Magenta,
    cyan = Fansi.palette.Cyan,
    orange = Fansi.palette.DarkYellow,
    dark_yellow = Fansi.palette.DarkYellow,
    dark_blue = Fansi.palette.DarkBlue,
    dark_magenta = Fansi.palette.DarkMagenta,
    dark_red = Fansi.palette.DarkRed,
    dark_green = Fansi.palette.DarkGreen,
    dark_cyan = Fansi.palette.DarkCyan,
    gray = Fansi.palette.Gray,
  }

  local config = Fansi.config

  ---@type table<string, HighlightDefinition>?
  local groups = {
    FansiFg0 = { ctermfg = colors.fg0 },
    FansiFg1 = { ctermfg = colors.fg1 },
    FansiFg2 = { ctermfg = colors.fg2 },
    FansiFg3 = { ctermfg = colors.fg3 },
    FansiFg4 = { ctermfg = colors.fg4 },
    FansiGray = { ctermfg = colors.gray },
    FansiBg0 = { ctermfg = colors.bg0 },
    FansiBg1 = { ctermfg = colors.bg1 },
    FansiBg2 = { ctermfg = colors.bg2 },
    FansiBg3 = { ctermfg = colors.bg3 },
    FansiBg4 = { ctermfg = colors.bg4 },
    FansiRed = { ctermfg = colors.red },
    FansiRedBold = { ctermfg = colors.red, bold = config.bold },
    FansiGreen = { ctermfg = colors.green },
    FansiGreenBold = { ctermfg = colors.green, bold = config.bold },
    FansiYellow = { ctermfg = colors.yellow },
    FansiYellowBold = { ctermfg = colors.yellow, bold = config.bold },
    FansiBlue = { ctermfg = colors.blue },
    FansiBlueBold = { ctermfg = colors.blue, bold = config.bold },
    FansiMagenta = { ctermfg = colors.magenta },
    FansiMagentaBold = { ctermfg = colors.magenta, bold = config.bold },
    FansiCyan = { ctermfg = colors.cyan },
    FansiCyanBold = { ctermfg = colors.cyan, bold = config.bold },
    FansiOrange = { ctermfg = colors.orange },
    FansiOrangeBold = { ctermfg = colors.orange, bold = config.bold },
    FansiRedSign = config.transparent_mode and { ctermfg = colors.red, reverse = config.invert_signs }
      or { ctermfg = colors.red, ctermbg = colors.bg1, reverse = config.invert_signs },
    FansiGreenSign = config.transparent_mode and { ctermfg = colors.green, reverse = config.invert_signs }
      or { ctermfg = colors.green, ctermbg = colors.bg1, reverse = config.invert_signs },
    FansiYellowSign = config.transparent_mode and { ctermfg = colors.yellow, reverse = config.invert_signs }
      or { ctermfg = colors.yellow, ctermbg = colors.bg1, reverse = config.invert_signs },
    FansiBlueSign = config.transparent_mode and { ctermfg = colors.blue, reverse = config.invert_signs }
      or { ctermfg = colors.blue, ctermbg = colors.bg1, reverse = config.invert_signs },
    FansiMagentaSign = config.transparent_mode and { ctermfg = colors.magenta, reverse = config.invert_signs }
      or { ctermfg = colors.magenta, ctermbg = colors.bg1, reverse = config.invert_signs },
    FansiCyanSign = config.transparent_mode and { ctermfg = colors.cyan, reverse = config.invert_signs }
      or { ctermfg = colors.cyan, ctermbg = colors.bg1, reverse = config.invert_signs },
    FansiOrangeSign = config.transparent_mode and { ctermfg = colors.orange, reverse = config.invert_signs }
      or { ctermfg = colors.orange, ctermbg = colors.bg1, reverse = config.invert_signs },
    -- TODO: these are wrong since we can't use the right values
    -- https://github.com/neovim/neovim/issues/23025
    FansiRedUnderline = { undercurl = config.undercurl, sp = "Red" },
    FansiGreenUnderline = { undercurl = config.undercurl, sp = "Green" },
    FansiYellowUnderline = { undercurl = config.undercurl, sp = "Yellow" },
    FansiBlueUnderline = { undercurl = config.undercurl, sp = "Blue" },
    FansiMagentaUnderline = { undercurl = config.undercurl, sp = "magenta" },
    FansiCyanUnderline = { undercurl = config.undercurl, sp = "cyan" },
    FansiOrangeUnderline = { undercurl = config.undercurl, sp = "Orange" },
    Normal = config.transparent_mode and { ctermfg = colors.fg1, ctermbg = nil }
      or { ctermfg = colors.fg1, ctermbg = colors.bg0 },
    NormalFloat = { ctermfg = colors.fg1 },
    FloatBorder = { ctermfg = colors.fg4 },
    FloatermBorder = { link = "FloatBorder" },
    NormalNC = config.dim_inactive and { ctermfg = colors.fg0, ctermbg = colors.bg1 } or { link = "Normal" },
    CursorLine = { ctermbg = colors.bg1 },
    CursorColumn = { link = "CursorLine" },
    TabLineFill = { ctermfg = colors.bg4, ctermbg = colors.bg1, reverse = config.invert_tabline },
    TabLineSel = { ctermfg = colors.green, ctermbg = colors.bg1, reverse = config.invert_tabline },
    TabLine = { link = "TabLineFill" },
    MatchParen = { ctermbg = colors.bg3, bold = config.bold },
    ColorColumn = { ctermbg = colors.bg1 },
    Conceal = { ctermfg = colors.blue },
    CursorLineNr = { ctermfg = colors.yellow, ctermbg = colors.bg1 },
    NonText = { link = "FansiBg3" },
    SpecialKey = { link = "FansiFg4" },
    Visual = { ctermbg = colors.bg3, reverse = config.invert_selection },
    VisualNOS = { link = "Visual" },
    Search = { ctermbg = colors.dark_yellow, ctermfg = colors.bg0 },
    IncSearch = { ctermbg = colors.magenta, ctermfg = colors.bg0 },
    CurSearch = { link = "IncSearch" },
    QuickFixLine = { link = "FansiMagenta" },
    Underlined = { ctermfg = colors.blue, underline = config.underline },
    StatusLine = { ctermfg = colors.fg4, ctermbg = colors.bg0 },
    StatusLineNC = { ctermfg = colors.bg0, ctermbg = colors.bg0 },
    WinBar = { ctermfg = colors.fg4, ctermbg = colors.bg0 },
    WinBarNC = { ctermfg = colors.fg3, ctermbg = colors.bg1 },
    WinSeparator = config.transparent_mode and { ctermfg = colors.bg3, ctermbg = nil }
      or { ctermfg = colors.bg3, ctermbg = colors.bg0 },
    WildMenu = { ctermfg = colors.blue, ctermbg = colors.bg2, bold = config.bold },
    Directory = { link = "FansiGreenBold" },
    Title = { link = "FansiGreenBold" },
    ErrorMsg = { ctermfg = colors.bg0, ctermbg = colors.red, bold = config.bold },
    MoreMsg = { link = "FansiYellowBold" },
    ModeMsg = { link = "FansiYellowBold" },
    Question = { link = "FansiOrangeBold" },
    WarningMsg = { link = "FansiRedBold" },
    LineNr = { ctermfg = colors.bg4 },
    SignColumn = config.transparent_mode and { ctermbg = nil } or { ctermbg = colors.bg1 },
    Folded = { ctermfg = colors.gray, ctermbg = colors.bg1, italic = config.italic.folds },
    FoldColumn = config.transparent_mode and { ctermfg = colors.gray, ctermbg = nil }
      or { ctermfg = colors.gray, ctermbg = colors.bg1 },
    Cursor = { reverse = config.inverse },
    vCursor = { link = "Cursor" },
    iCursor = { link = "Cursor" },
    lCursor = { link = "Cursor" },
    Special = { ctermfg = colors.magenta },
    Comment = { ctermfg = colors.gray, italic = config.italic.comments },
    Todo = { ctermfg = colors.bg0, ctermbg = colors.yellow, bold = config.bold, italic = config.italic.comments },
    Done = { ctermfg = colors.orange, bold = config.bold, italic = config.italic.comments },
    Error = { ctermfg = colors.red, bold = config.bold, reverse = config.inverse },
    Statement = { link = "FansiRed" },
    Conditional = { link = "FansiRed" },
    Repeat = { link = "FansiRed" },
    Label = { link = "FansiRed" },
    Exception = { link = "FansiRed" },
    Operator = { ctermfg = colors.dark_yellow, italic = config.italic.operators },
    Keyword = { link = "FansiRed" },
    Identifier = { link = "FansiBlue" },
    Function = { link = "FansiGreenBold" },
    PreProc = { link = "FansiCyan" },
    Include = { link = "FansiCyan" },
    Define = { link = "FansiCyan" },
    Macro = { link = "FansiCyan" },
    PreCondit = { link = "FansiCyan" },
    Constant = { link = "FansiMagenta" },
    Character = { link = "FansiMagenta" },
    String = { ctermfg = colors.green, italic = config.italic.strings },
    Boolean = { link = "FansiMagenta" },
    Number = { link = "FansiMagenta" },
    Float = { link = "FansiMagenta" },
    Type = { link = "FansiYellow" },
    StorageClass = { link = "FansiOrange" },
    Structure = { link = "FansiCyan" },
    Typedef = { link = "FansiYellow" },
    Pmenu = { ctermfg = colors.fg1, ctermbg = colors.bg2 },
    PmenuSel = { ctermfg = colors.bg2, ctermbg = colors.blue, bold = config.bold },
    PmenuSbar = { ctermbg = colors.bg2 },
    PmenuThumb = { ctermbg = colors.bg4 },
    DiffDelete = { ctermbg = colors.dark_red, blend = 50 },
    DiffAdd = { ctermbg = colors.dark_green, blend = 50 },
    DiffChange = { ctermbg = colors.dark_cyan, blend = 50 },
    DiffText = { ctermbg = colors.yellow, ctermfg = colors.bg0 },
    SpellCap = { link = "FansiBlueUnderline" },
    SpellBad = { link = "FansiRedUnderline" },
    SpellLocal = { link = "FansiCyanUnderline" },
    SpellRare = { link = "FansiMagentaUnderline" },
    Whitespace = { ctermfg = colors.bg2 },
    Delimiter = { ctermfg = colors.fg2 },
    EndOfBuffer = { link = "NonText" },
    DiagnosticError = { link = "FansiRed" },
    DiagnosticSignError = { link = "FansiRedSign" },
    DiagnosticUnderlineError = { link = "FansiRedUnderline" },
    DiagnosticWarn = { link = "FansiYellow" },
    DiagnosticSignWarn = { link = "FansiYellowSign" },
    DiagnosticUnderlineWarn = { link = "FansiYellowUnderline" },
    DiagnosticInfo = { link = "FansiBlue" },
    DiagnosticSignInfo = { link = "FansiBlueSign" },
    DiagnosticUnderlineInfo = { link = "FansiBlueUnderline" },
    DiagnosticHint = { link = "FansiCyan" },
    DiagnosticSignHint = { link = "FansiCyanSign" },
    DiagnosticUnderlineHint = { link = "FansiCyanUnderline" },
    DiagnosticFloatingError = { link = "FansiRed" },
    DiagnosticFloatingWarn = { link = "FansiOrange" },
    DiagnosticFloatingInfo = { link = "FansiBlue" },
    DiagnosticFloatingHint = { link = "FansiCyan" },
    DiagnosticVirtualTextError = { ctermfg = colors.dark_red },
    DiagnosticVirtualTextWarn = { ctermfg = colors.dark_yellow },
    DiagnosticVirtualTextInfo = { ctermfg = colors.dark_blue },
    DiagnosticVirtualTextHint = { ctermfg = colors.dark_cyan },
    DiagnosticOk = { link = "FansiGreenSign" },
    LspReferenceRead = { link = "FansiYellowBold" },
    LspReferenceText = { link = "FansiYellowBold" },
    LspReferenceWrite = { link = "FansiOrangeBold" },
    LspCodeLens = { link = "FansiGray" },
    LspSignatureActiveParameter = { link = "Search" },
    gitcommitSelectedFile = { link = "FansiGreen" },
    gitcommitDiscardedFile = { link = "FansiRed" },
    GitSignsAdd = { link = "FansiGreen" },
    GitSignsChange = { link = "FansiOrange" },
    GitSignsDelete = { link = "FansiRed" },
    NvimTreeSymlink = { ctermfg = colors.dark_cyan },
    NvimTreeRootFolder = { ctermfg = colors.dark_magenta, bold = true },
    NvimTreeFolderIcon = { ctermfg = colors.dark_blue, bold = true },
    NvimTreeFileIcon = { ctermfg = colors.light2 },
    NvimTreeExecFile = { ctermfg = colors.dark_green, bold = true },
    NvimTreeOpenedFile = { ctermfg = colors.bright_red, bold = true },
    NvimTreeSpecialFile = { ctermfg = colors.dark_yellow, bold = true, underline = true },
    NvimTreeImageFile = { ctermfg = colors.dark_magenta },
    NvimTreeIndentMarker = { ctermfg = colors.dark3 },
    NvimTreeGitDirty = { ctermfg = colors.dark_yellow },
    NvimTreeGitStaged = { ctermfg = colors.dark_yellow },
    NvimTreeGitMerge = { ctermfg = colors.dark_magenta },
    NvimTreeGitRenamed = { ctermfg = colors.dark_magenta },
    NvimTreeGitNew = { ctermfg = colors.dark_yellow },
    NvimTreeGitDeleted = { ctermfg = colors.dark_red },
    NvimTreeWindowPicker = { ctermbg = colors.cyan },
    debugPC = { link = "DiffAdd" },
    debugBreakpoint = { link = "FansiRedSign" },
    StartifyBracket = { link = "FansiFg3" },
    StartifyFile = { link = "FansiFg1" },
    StartifyNumber = { link = "FansiBlue" },
    StartifyPath = { link = "FansiGray" },
    StartifySlash = { link = "FansiGray" },
    StartifySection = { link = "FansiYellow" },
    StartifySpecial = { link = "FansiBg2" },
    StartifyHeader = { link = "FansiOrange" },
    StartifyFooter = { link = "FansiBg2" },
    StartifyVar = { link = "StartifyPath" },
    StartifySelect = { link = "Title" },
    DirvishPathTail = { link = "FansiCyan" },
    DirvishArg = { link = "FansiYellow" },
    netrwDir = { link = "FansiCyan" },
    netrwClassify = { link = "FansiCyan" },
    netrwLink = { link = "FansiGray" },
    netrwSymLink = { link = "FansiFg1" },
    netrwExe = { link = "FansiYellow" },
    netrwComment = { link = "FansiGray" },
    netrwList = { link = "FansiBlue" },
    netrwHelpCmd = { link = "FansiCyan" },
    netrwCmdSep = { link = "FansiFg3" },
    netrwVersion = { link = "FansiGreen" },
    NERDTreeDir = { link = "FansiCyan" },
    NERDTreeDirSlash = { link = "FansiCyan" },
    NERDTreeOpenable = { link = "FansiOrange" },
    NERDTreeClosable = { link = "FansiOrange" },
    NERDTreeFile = { link = "FansiFg1" },
    NERDTreeExecFile = { link = "FansiYellow" },
    NERDTreeUp = { link = "FansiGray" },
    NERDTreeCWD = { link = "FansiGreen" },
    NERDTreeHelp = { link = "FansiFg1" },
    NERDTreeToggleOn = { link = "FansiGreen" },
    NERDTreeToggleOff = { link = "FansiRed" },
    CocErrorSign = { link = "FansiRedSign" },
    CocWarningSign = { link = "FansiOrangeSign" },
    CocInfoSign = { link = "FansiBlueSign" },
    CocHintSign = { link = "FansiCyanSign" },
    CocErrorFloat = { link = "FansiRed" },
    CocWarningFloat = { link = "FansiOrange" },
    CocInfoFloat = { link = "FansiBlue" },
    CocHintFloat = { link = "FansiCyan" },
    CocDiagnosticsError = { link = "FansiRed" },
    CocDiagnosticsWarning = { link = "FansiOrange" },
    CocDiagnosticsInfo = { link = "FansiBlue" },
    CocDiagnosticsHint = { link = "FansiCyan" },
    CocSelectedText = { link = "FansiRed" },
    CocMenuSel = { link = "PmenuSel" },
    CocCodeLens = { link = "FansiGray" },
    CocErrorHighlight = { link = "FansiRedUnderline" },
    CocWarningHighlight = { link = "FansiOrangeUnderline" },
    CocInfoHighlight = { link = "FansiBlueUnderline" },
    CocHintHighlight = { link = "FansiCyanUnderline" },
    TelescopeNormal = { link = "FansiFg1" },
    TelescopeSelection = { link = "FansiOrangeBold" },
    TelescopeSelectionCaret = { link = "FansiRed" },
    TelescopeMultiSelection = { link = "FansiGray" },
    TelescopeBorder = { link = "TelescopeNormal" },
    TelescopePromptBorder = { link = "TelescopeNormal" },
    TelescopeResultsBorder = { link = "TelescopeNormal" },
    TelescopePreviewBorder = { link = "TelescopeNormal" },
    TelescopeMatching = { link = "FansiBlue" },
    TelescopePromptPrefix = { link = "FansiRed" },
    TelescopePrompt = { link = "TelescopeNormal" },
    CmpItemAbbr = { link = "FansiFg0" },
    CmpItemAbbrDeprecated = { link = "FansiFg1" },
    CmpItemAbbrMatch = { link = "FansiBlueBold" },
    CmpItemAbbrMatchFuzzy = { link = "FansiBlueUnderline" },
    CmpItemMenu = { link = "FansiGray" },
    CmpItemKindText = { link = "FansiOrange" },
    CmpItemKindVariable = { link = "FansiOrange" },
    CmpItemKindMethod = { link = "FansiBlue" },
    CmpItemKindFunction = { link = "FansiBlue" },
    CmpItemKindConstructor = { link = "FansiYellow" },
    CmpItemKindUnit = { link = "FansiBlue" },
    CmpItemKindField = { link = "FansiBlue" },
    CmpItemKindClass = { link = "FansiYellow" },
    CmpItemKindInterface = { link = "FansiYellow" },
    CmpItemKindModule = { link = "FansiBlue" },
    CmpItemKindProperty = { link = "FansiBlue" },
    CmpItemKindValue = { link = "FansiOrange" },
    CmpItemKindEnum = { link = "FansiYellow" },
    CmpItemKindOperator = { link = "FansiYellow" },
    CmpItemKindKeyword = { link = "FansiMagenta" },
    CmpItemKindEvent = { link = "FansiMagenta" },
    CmpItemKindReference = { link = "FansiMagenta" },
    CmpItemKindColor = { link = "FansiMagenta" },
    CmpItemKindSnippet = { link = "FansiGreen" },
    CmpItemKindFile = { link = "FansiBlue" },
    CmpItemKindFolder = { link = "FansiBlue" },
    CmpItemKindEnumMember = { link = "FansiCyan" },
    CmpItemKindConstant = { link = "FansiOrange" },
    CmpItemKindStruct = { link = "FansiYellow" },
    CmpItemKindTypeParameter = { link = "FansiYellow" },
    diffAdded = { link = "DiffAdd" },
    diffRemoved = { link = "DiffDelete" },
    diffChanged = { link = "DiffChange" },
    diffFile = { link = "FansiOrange" },
    diffNewFile = { link = "FansiYellow" },
    diffOldFile = { link = "FansiOrange" },
    diffLine = { link = "FansiBlue" },
    diffIndexLine = { link = "diffChanged" },
    NavicIconsFile = { link = "FansiBlue" },
    NavicIconsModule = { link = "FansiOrange" },
    NavicIconsNamespace = { link = "FansiBlue" },
    NavicIconsPackage = { link = "FansiCyan" },
    NavicIconsClass = { link = "FansiYellow" },
    NavicIconsMethod = { link = "FansiBlue" },
    NavicIconsProperty = { link = "FansiCyan" },
    NavicIconsField = { link = "FansiMagenta" },
    NavicIconsConstructor = { link = "FansiBlue" },
    NavicIconsEnum = { link = "FansiMagenta" },
    NavicIconsInterface = { link = "FansiGreen" },
    NavicIconsFunction = { link = "FansiBlue" },
    NavicIconsVariable = { link = "FansiMagenta" },
    NavicIconsConstant = { link = "FansiOrange" },
    NavicIconsString = { link = "FansiGreen" },
    NavicIconsNumber = { link = "FansiOrange" },
    NavicIconsBoolean = { link = "FansiOrange" },
    NavicIconsArray = { link = "FansiOrange" },
    NavicIconsObject = { link = "FansiOrange" },
    NavicIconsKey = { link = "FansiCyan" },
    NavicIconsNull = { link = "FansiOrange" },
    NavicIconsEnumMember = { link = "FansiYellow" },
    NavicIconsStruct = { link = "FansiMagenta" },
    NavicIconsEvent = { link = "FansiYellow" },
    NavicIconsOperator = { link = "FansiRed" },
    NavicIconsTypeParameter = { link = "FansiRed" },
    NavicText = { link = "FansiWhite" },
    NavicSeparator = { link = "FansiWhite" },
    htmlTag = { link = "FansiCyanBold" },
    htmlEndTag = { link = "FansiCyanBold" },
    htmlTagName = { link = "FansiBlue" },
    htmlArg = { link = "FansiOrange" },
    htmlTagN = { link = "FansiFg1" },
    htmlSpecialTagName = { link = "FansiBlue" },
    htmlLink = { ctermfg = colors.fg4, underline = config.underline },
    htmlSpecialChar = { link = "FansiRed" },
    htmlBold = { ctermfg = colors.fg0, ctermbg = colors.bg0, bold = config.bold },
    htmlBoldUnderline = { ctermfg = colors.fg0, ctermbg = colors.bg0, bold = config.bold, underline = config.underline },
    htmlBoldItalic = { ctermfg = colors.fg0, ctermbg = colors.bg0, bold = config.bold, italic = true },
    htmlBoldUnderlineItalic = {
      ctermfg = colors.fg0,
      ctermbg = colors.bg0,
      bold = config.bold,
      italic = true,
      underline = config.underline,
    },
    htmlUnderline = { ctermfg = colors.fg0, ctermbg = colors.bg0, underline = config.underline },
    htmlUnderlineItalic = {
      ctermfg = colors.fg0,
      ctermbg = colors.bg0,
      italic = true,
      underline = config.underline,
    },
    htmlItalic = { ctermfg = colors.fg0, ctermbg = colors.bg0, italic = true },
    xmlTag = { link = "FansiCyanBold" },
    xmlEndTag = { link = "FansiCyanBold" },
    xmlTagName = { link = "FansiBlue" },
    xmlEqual = { link = "FansiBlue" },
    docbkKeyword = { link = "FansiCyanBold" },
    xmlDocTypeDecl = { link = "FansiGray" },
    xmlDocTypeKeyword = { link = "FansiMagenta" },
    xmlCdataStart = { link = "FansiGray" },
    xmlCdataCdata = { link = "FansiMagenta" },
    dtdFunction = { link = "FansiGray" },
    dtdTagName = { link = "FansiMagenta" },
    xmlAttrib = { link = "FansiOrange" },
    xmlProcessingDelim = { link = "FansiGray" },
    dtdParamEntityPunct = { link = "FansiGray" },
    dtdParamEntityDPunct = { link = "FansiGray" },
    xmlAttribPunct = { link = "FansiGray" },
    xmlEntity = { link = "FansiRed" },
    xmlEntityPunct = { link = "FansiRed" },
    clojureKeyword = { link = "FansiBlue" },
    clojureCond = { link = "FansiOrange" },
    clojureSpecial = { link = "FansiOrange" },
    clojureDefine = { link = "FansiOrange" },
    clojureFunc = { link = "FansiYellow" },
    clojureRepeat = { link = "FansiYellow" },
    clojureCharacter = { link = "FansiCyan" },
    clojureStringEscape = { link = "FansiCyan" },
    clojureException = { link = "FansiRed" },
    clojureRegexp = { link = "FansiCyan" },
    clojureRegexpEscape = { link = "FansiCyan" },
    clojureRegexpCharClass = { ctermfg = colors.fg3, bold = config.bold },
    clojureRegexpMod = { link = "clojureRegexpCharClass" },
    clojureRegexpQuantifier = { link = "clojureRegexpCharClass" },
    clojureParen = { link = "FansiFg3" },
    clojureAnonArg = { link = "FansiYellow" },
    clojureVariable = { link = "FansiBlue" },
    clojureMacro = { link = "FansiOrange" },
    clojureMeta = { link = "FansiYellow" },
    clojureDeref = { link = "FansiYellow" },
    clojureQuote = { link = "FansiYellow" },
    clojureUnquote = { link = "FansiYellow" },
    cOperator = { link = "FansiMagenta" },
    cppOperator = { link = "FansiMagenta" },
    cStructure = { link = "FansiOrange" },
    pythonBuiltin = { link = "FansiOrange" },
    pythonBuiltinObj = { link = "FansiOrange" },
    pythonBuiltinFunc = { link = "FansiOrange" },
    pythonFunction = { link = "FansiCyan" },
    pythonDecorator = { link = "FansiRed" },
    pythonInclude = { link = "FansiBlue" },
    pythonImport = { link = "FansiBlue" },
    pythonRun = { link = "FansiBlue" },
    pythonCoding = { link = "FansiBlue" },
    pythonOperator = { link = "FansiRed" },
    pythonException = { link = "FansiRed" },
    pythonExceptions = { link = "FansiMagenta" },
    pythonBoolean = { link = "FansiMagenta" },
    pythonDot = { link = "FansiFg3" },
    pythonConditional = { link = "FansiRed" },
    pythonRepeat = { link = "FansiRed" },
    pythonDottedName = { link = "FansiGreenBold" },
    cssBraces = { link = "FansiBlue" },
    cssFunctionName = { link = "FansiYellow" },
    cssIdentifier = { link = "FansiOrange" },
    cssClassName = { link = "FansiGreen" },
    cssColor = { link = "FansiBlue" },
    cssSelectorOp = { link = "FansiBlue" },
    cssSelectorOp2 = { link = "FansiBlue" },
    cssImportant = { link = "FansiGreen" },
    cssVendor = { link = "FansiFg1" },
    cssTextProp = { link = "FansiCyan" },
    cssAnimationProp = { link = "FansiCyan" },
    cssUIProp = { link = "FansiYellow" },
    cssTransformProp = { link = "FansiCyan" },
    cssTransitionProp = { link = "FansiCyan" },
    cssPrintProp = { link = "FansiCyan" },
    cssPositioningProp = { link = "FansiYellow" },
    cssBoxProp = { link = "FansiCyan" },
    cssFontDescriptorProp = { link = "FansiCyan" },
    cssFlexibleBoxProp = { link = "FansiCyan" },
    cssBorderOutlineProp = { link = "FansiCyan" },
    cssBackgroundProp = { link = "FansiCyan" },
    cssMarginProp = { link = "FansiCyan" },
    cssListProp = { link = "FansiCyan" },
    cssTableProp = { link = "FansiCyan" },
    cssFontProp = { link = "FansiCyan" },
    cssPaddingProp = { link = "FansiCyan" },
    cssDimensionProp = { link = "FansiCyan" },
    cssRenderProp = { link = "FansiCyan" },
    cssColorProp = { link = "FansiCyan" },
    cssGeneratedContentProp = { link = "FansiCyan" },
    javaScriptBraces = { link = "FansiFg1" },
    javaScriptFunction = { link = "FansiCyan" },
    javaScriptIdentifier = { link = "FansiRed" },
    javaScriptMember = { link = "FansiBlue" },
    javaScriptNumber = { link = "FansiMagenta" },
    javaScriptNull = { link = "FansiMagenta" },
    javaScriptParens = { link = "FansiFg3" },
    typescriptReserved = { link = "FansiCyan" },
    typescriptLabel = { link = "FansiCyan" },
    typescriptFuncKeyword = { link = "FansiCyan" },
    typescriptIdentifier = { link = "FansiOrange" },
    typescriptBraces = { link = "FansiFg1" },
    typescriptEndColons = { link = "FansiFg1" },
    typescriptDOMObjects = { link = "FansiFg1" },
    typescriptAjaxMethods = { link = "FansiFg1" },
    typescriptLogicSymbols = { link = "FansiFg1" },
    typescriptDocSeeTag = { link = "Comment" },
    typescriptDocParam = { link = "Comment" },
    typescriptDocTags = { link = "vimCommentTitle" },
    typescriptGlobalObjects = { link = "FansiFg1" },
    typescriptParens = { link = "FansiFg3" },
    typescriptOpSymbols = { link = "FansiFg3" },
    typescriptHtmlElemProperties = { link = "FansiFg1" },
    typescriptNull = { link = "FansiMagenta" },
    typescriptInterpolationDelimiter = { link = "FansiCyan" },
    purescriptModuleKeyword = { link = "FansiCyan" },
    purescriptModuleName = { link = "FansiFg1" },
    purescriptWhere = { link = "FansiCyan" },
    purescriptDelimiter = { link = "FansiFg4" },
    purescriptType = { link = "FansiFg1" },
    purescriptImportKeyword = { link = "FansiCyan" },
    purescriptHidingKeyword = { link = "FansiCyan" },
    purescriptAsKeyword = { link = "FansiCyan" },
    purescriptStructure = { link = "FansiCyan" },
    purescriptOperator = { link = "FansiBlue" },
    purescriptTypeVar = { link = "FansiFg1" },
    purescriptConstructor = { link = "FansiFg1" },
    purescriptFunction = { link = "FansiFg1" },
    purescriptConditional = { link = "FansiOrange" },
    purescriptBacktick = { link = "FansiOrange" },
    coffeeExtendedOp = { link = "FansiFg3" },
    coffeeSpecialOp = { link = "FansiFg3" },
    coffeeCurly = { link = "FansiOrange" },
    coffeeParen = { link = "FansiFg3" },
    coffeeBracket = { link = "FansiOrange" },
    rubyStringDelimiter = { link = "FansiGreen" },
    rubyInterpolationDelimiter = { link = "FansiCyan" },
    rubyDefinedOperator = { link = "rubyKeyword" },
    objcTypeModifier = { link = "FansiRed" },
    objcDirective = { link = "FansiBlue" },
    goDirective = { link = "FansiCyan" },
    goConstants = { link = "FansiMagenta" },
    goDeclaration = { link = "FansiRed" },
    goDeclType = { link = "FansiBlue" },
    goBuiltins = { link = "FansiOrange" },
    luaIn = { link = "FansiRed" },
    luaFunction = { link = "FansiCyan" },
    luaTable = { link = "FansiOrange" },
    moonSpecialOp = { link = "FansiFg3" },
    moonExtendedOp = { link = "FansiFg3" },
    moonFunction = { link = "FansiFg3" },
    moonObject = { link = "FansiYellow" },
    javaAnnotation = { link = "FansiBlue" },
    javaDocTags = { link = "FansiCyan" },
    javaCommentTitle = { link = "vimCommentTitle" },
    javaParen = { link = "FansiFg3" },
    javaParen1 = { link = "FansiFg3" },
    javaParen2 = { link = "FansiFg3" },
    javaParen3 = { link = "FansiFg3" },
    javaParen4 = { link = "FansiFg3" },
    javaParen5 = { link = "FansiFg3" },
    javaOperator = { link = "FansiOrange" },
    javaVarArg = { link = "FansiGreen" },
    elixirDocString = { link = "Comment" },
    elixirStringDelimiter = { link = "FansiGreen" },
    elixirInterpolationDelimiter = { link = "FansiCyan" },
    elixirModuleDeclaration = { link = "FansiYellow" },
    scalaNameDefinition = { link = "FansiFg1" },
    scalaCaseFollowing = { link = "FansiFg1" },
    scalaCapitalWord = { link = "FansiFg1" },
    scalaTypeExtension = { link = "FansiFg1" },
    scalaKeyword = { link = "FansiRed" },
    scalaKeywordModifier = { link = "FansiRed" },
    scalaSpecial = { link = "FansiCyan" },
    scalaOperator = { link = "FansiFg1" },
    scalaTypeDeclaration = { link = "FansiYellow" },
    scalaTypeTypePostDeclaration = { link = "FansiYellow" },
    scalaInstanceDeclaration = { link = "FansiFg1" },
    scalaInterpolation = { link = "FansiCyan" },
    markdownItalic = { ctermfg = colors.fg3, italic = true },
    markdownBold = { ctermfg = colors.fg3, bold = config.bold },
    markdownBoldItalic = { ctermfg = colors.fg3, bold = config.bold, italic = true },
    markdownH1 = { link = "FansiGreenBold" },
    markdownH2 = { link = "FansiGreenBold" },
    markdownH3 = { link = "FansiYellowBold" },
    markdownH4 = { link = "FansiYellowBold" },
    markdownH5 = { link = "FansiYellow" },
    markdownH6 = { link = "FansiYellow" },
    markdownCode = { link = "FansiCyan" },
    markdownCodeBlock = { link = "FansiCyan" },
    markdownCodeDelimiter = { link = "FansiCyan" },
    markdownBlockquote = { link = "FansiGray" },
    markdownListMarker = { link = "FansiGray" },
    markdownOrderedListMarker = { link = "FansiGray" },
    markdownRule = { link = "FansiGray" },
    markdownHeadingRule = { link = "FansiGray" },
    markdownUrlDelimiter = { link = "FansiFg3" },
    markdownLinkDelimiter = { link = "FansiFg3" },
    markdownLinkTextDelimiter = { link = "FansiFg3" },
    markdownHeadingDelimiter = { link = "FansiOrange" },
    markdownUrl = { link = "FansiMagenta" },
    markdownUrlTitleDelimiter = { link = "FansiGreen" },
    markdownLinkText = { ctermfg = colors.gray, underline = config.underline },
    markdownIdDeclaration = { link = "markdownLinkText" },
    haskellType = { link = "FansiBlue" },
    haskellIdentifier = { link = "FansiCyan" },
    haskellSeparator = { link = "FansiFg4" },
    haskellDelimiter = { link = "FansiOrange" },
    haskellOperators = { link = "FansiMagenta" },
    haskellBacktick = { link = "FansiOrange" },
    haskellStatement = { link = "FansiMagenta" },
    haskellConditional = { link = "FansiMagenta" },
    haskellLet = { link = "FansiRed" },
    haskellDefault = { link = "FansiRed" },
    haskellWhere = { link = "FansiRed" },
    haskellBottom = { link = "FansiRedBold" },
    haskellImportKeywords = { link = "FansiMagentaBold" },
    haskellDeclKeyword = { link = "FansiOrange" },
    haskellDecl = { link = "FansiOrange" },
    haskellDeriving = { link = "FansiMagenta" },
    haskellAssocType = { link = "FansiCyan" },
    haskellNumber = { link = "FansiCyan" },
    haskellPragma = { link = "FansiRedBold" },
    haskellTH = { link = "FansiCyanBold" },
    haskellForeignKeywords = { link = "FansiGreen" },
    haskellKeyword = { link = "FansiRed" },
    haskellFloat = { link = "FansiCyan" },
    haskellInfix = { link = "FansiMagenta" },
    haskellQuote = { link = "FansiGreenBold" },
    haskellShebang = { link = "FansiYellowBold" },
    haskellLiquid = { link = "FansiMagentaBold" },
    haskellQuasiQuoted = { link = "FansiBlueBold" },
    haskellRecursiveDo = { link = "FansiMagenta" },
    haskellQuotedType = { link = "FansiRed" },
    haskellPreProc = { link = "FansiFg4" },
    haskellTypeRoles = { link = "FansiRedBold" },
    haskellTypeForall = { link = "FansiRed" },
    haskellPatternKeyword = { link = "FansiBlue" },
    jsonKeyword = { link = "FansiGreen" },
    jsonQuote = { link = "FansiGreen" },
    jsonBraces = { link = "FansiFg1" },
    jsonString = { link = "FansiFg1" },
    mailQuoted1 = { link = "FansiCyan" },
    mailQuoted2 = { link = "FansiMagenta" },
    mailQuoted3 = { link = "FansiYellow" },
    mailQuoted4 = { link = "FansiGreen" },
    mailQuoted5 = { link = "FansiRed" },
    mailQuoted6 = { link = "FansiOrange" },
    mailSignature = { link = "Comment" },
    csBraces = { link = "FansiFg1" },
    csEndColon = { link = "FansiFg1" },
    csLogicSymbols = { link = "FansiFg1" },
    csParens = { link = "FansiFg3" },
    csOpSymbols = { link = "FansiFg3" },
    csInterpolationDelimiter = { link = "FansiFg3" },
    csInterpolationAlignDel = { link = "FansiCyanBold" },
    csInterpolationFormat = { link = "FansiCyan" },
    csInterpolationFormatDel = { link = "FansiCyanBold" },
    rustSigil = { link = "FansiOrange" },
    rustEscape = { link = "FansiCyan" },
    rustStringContinuation = { link = "FansiCyan" },
    rustEnum = { link = "FansiCyan" },
    rustStructure = { link = "FansiCyan" },
    rustModPathSep = { link = "FansiFg2" },
    rustCommentLineDoc = { link = "Comment" },
    rustDefault = { link = "FansiCyan" },
    ocamlOperator = { link = "FansiFg1" },
    ocamlKeyChar = { link = "FansiOrange" },
    ocamlArrow = { link = "FansiOrange" },
    ocamlInfixOpKeyword = { link = "FansiRed" },
    ocamlConstructor = { link = "FansiOrange" },
    LspSagaCodeActionTitle = { link = "Title" },
    LspSagaCodeActionBorder = { link = "FansiFg1" },
    LspSagaCodeActionContent = { ctermfg = colors.green, bold = config.bold },
    LspSagaLspFinderBorder = { link = "FansiFg1" },
    LspSagaAutoPreview = { link = "FansiOrange" },
    TargetWord = { ctermfg = colors.blue, bold = config.bold },
    FinderSeparator = { link = "FansiCyan" },
    LspSagaDefPreviewBorder = { link = "FansiBlue" },
    LspSagaHoverBorder = { link = "FansiOrange" },
    LspSagaRenameBorder = { link = "FansiBlue" },
    LspSagaDiagnosticSource = { link = "FansiOrange" },
    LspSagaDiagnosticBorder = { link = "FansiMagenta" },
    LspSagaDiagnosticHeader = { link = "FansiGreen" },
    LspSagaSignatureHelpBorder = { link = "FansiGreen" },
    SagaShadow = { link = "FansiBg0" },
    DashboardShortCut = { link = "FansiOrange" },
    DashboardHeader = { link = "FansiCyan" },
    DashboardCenter = { link = "FansiYellow" },
    DashboardFooter = { ctermfg = colors.magenta, italic = true },
    MasonHighlight = { link = "FansiCyan" },
    MasonHighlightBlock = { ctermfg = colors.bg0, ctermbg = colors.blue },
    MasonHighlightBlockBold = { ctermfg = colors.bg0, ctermbg = colors.blue, bold = true },
    MasonHighlightSecondary = { ctermfg = colors.yellow },
    MasonHighlightBlockSecondary = { ctermfg = colors.bg0, ctermbg = colors.yellow },
    MasonHighlightBlockBoldSecondary = { ctermfg = colors.bg0, ctermbg = colors.yellow, bold = true },
    MasonHeader = { link = "MasonHighlightBlockBoldSecondary" },
    MasonHeaderSecondary = { link = "MasonHighlightBlockBold" },
    MasonMuted = { ctermfg = colors.fg4 },
    MasonMutedBlock = { ctermfg = colors.bg0, ctermbg = colors.fg4 },
    MasonMutedBlockBold = { ctermfg = colors.bg0, ctermbg = colors.fg4, bold = true },
    LspInlayHint = { link = "comment" },
    CarbonFile = { link = "FansiFg1" },
    CarbonExe = { link = "FansiYellow" },
    CarbonSymlink = { link = "FansiCyan" },
    CarbonBrokenSymlink = { link = "FansiRed" },
    CarbonIndicator = { link = "FansiGray" },
    CarbonDanger = { link = "FansiRed" },
    CarbonPending = { link = "FansiYellow" },
    NoiceCursor = { link = "TermCursor" },
    NoiceCmdlinePopupBorder = { ctermfg = colors.blue, ctermbg = nil },
    NoiceCmdlineIcon = { link = "NoiceCmdlinePopupBorder" },
    NoiceConfirmBorder = { link = "NoiceCmdlinePopupBorder" },
    NoiceCmdlinePopupBorderSearch = { ctermfg = colors.yellow, ctermbg = nil },
    NoiceCmdlineIconSearch = { link = "NoiceCmdlinePopupBorderSearch" },
    NotifyDEBUGBorder = { link = "FansiBlue" },
    NotifyDEBUGIcon = { link = "FansiBlue" },
    NotifyDEBUGTitle = { link = "FansiBlue" },
    NotifyERRORBorder = { link = "FansiRed" },
    NotifyERRORIcon = { link = "FansiRed" },
    NotifyERRORTitle = { link = "FansiRed" },
    NotifyINFOBorder = { link = "FansiCyan" },
    NotifyINFOIcon = { link = "FansiCyan" },
    NotifyINFOTitle = { link = "FansiCyan" },
    NotifyTRACEBorder = { link = "FansiGreen" },
    NotifyTRACEIcon = { link = "FansiGreen" },
    NotifyTRACETitle = { link = "FansiGreen" },
    NotifyWARNBorder = { link = "FansiYellow" },
    NotifyWARNIcon = { link = "FansiYellow" },
    NotifyWARNTitle = { link = "FansiYellow" },
    IlluminatedWordText = { link = "LspReferenceText" },
    IlluminatedWordRead = { link = "LspReferenceRead" },
    IlluminatedWordWrite = { link = "LspReferenceWrite" },
    TSRainbowRed = { ctermfg = colors.red },
    TSRainbowOrange = { ctermfg = colors.orange },
    TSRainbowYellow = { ctermfg = colors.yellow },
    TSRainbowGreen = { ctermfg = colors.green },
    TSRainbowBlue = { ctermfg = colors.blue },
    TSRainbowViolet = { ctermfg = colors.magenta },
    TSRainbowCyan = { ctermfg = colors.cyan },
    RainbowDelimiterRed = { ctermfg = colors.red },
    RainbowDelimiterOrange = { ctermfg = colors.orange },
    RainbowDelimiterYellow = { ctermfg = colors.yellow },
    RainbowDelimiterGreen = { ctermfg = colors.green },
    RainbowDelimiterBlue = { ctermfg = colors.blue },
    RainbowDelimiterViolet = { ctermfg = colors.magenta },
    RainbowDelimiterCyan = { ctermfg = colors.cyan },
    DapBreakpointSymbol = { ctermfg = colors.red, ctermbg = colors.bg1 },
    DapStoppedSymbol = { ctermfg = colors.green, ctermbg = colors.bg1 },
    DapUIBreakpointsCurrentLine = { link = "FansiYellow" },
    DapUIBreakpointsDisabledLine = { link = "FansiGray" },
    DapUIBreakpointsInfo = { link = "FansiCyan" },
    DapUIBreakpointsLine = { link = "FansiYellow" },
    DapUIBreakpointsPath = { link = "FansiBlue" },
    DapUICurrentFrameName = { link = "FansiMagenta" },
    DapUIDecoration = { link = "FansiMagenta" },
    DapUIEndofBuffer = { link = "EndOfBuffer" },
    DapUIFloatBorder = { link = "FansiCyan" },
    DapUILineNumber = { link = "FansiYellow" },
    DapUIModifiedValue = { link = "FansiRed" },
    DapUIPlayPause = { ctermfg = colors.green, ctermbg = colors.bg1 },
    DapUIRestart = { ctermfg = colors.green, ctermbg = colors.bg1 },
    DapUIScope = { link = "FansiBlue" },
    DapUISource = { link = "FansiFg1" },
    DapUIStepBack = { ctermfg = colors.blue, ctermbg = colors.bg1 },
    DapUIStepInto = { ctermfg = colors.blue, ctermbg = colors.bg1 },
    DapUIStepOut = { ctermfg = colors.blue, ctermbg = colors.bg1 },
    DapUIStepOver = { ctermfg = colors.blue, ctermbg = colors.bg1 },
    DapUIStop = { ctermfg = colors.red, ctermbg = colors.bg1 },
    DapUIStoppedThread = { link = "FansiBlue" },
    DapUIThread = { link = "FansiBlue" },
    DapUIType = { link = "FansiOrange" },
    DapUIUnavailable = { link = "FansiGray" },
    DapUIWatchesEmpty = { link = "FansiGray" },
    DapUIWatchesError = { link = "FansiRed" },
    DapUIWatchesValue = { link = "FansiYellow" },
    DapUIWinSelect = { link = "FansiYellow" },
    NeogitDiffDelete = { link = "DiffDelete" },
    NeogitDiffAdd = { link = "DiffAdd" },
    NeogitHunkHeader = { link = "WinBar" },
    NeogitHunkHeaderHighlight = { link = "WinBarNC" },
    DiffviewStatusModified = { link = "FansiGreenBold" },
    DiffviewFilePanelInsertions = { link = "FansiGreenBold" },
    DiffviewFilePanelDeletions = { link = "FansiRedBold" },
    MiniAnimateCursor = { reverse = true, nocombine = true },
    MiniAnimateNormalFloat = { ctermfg = colors.fg1, ctermbg = colors.bg1 },
    MiniClueBorder = { link = "FloatBorder" },
    MiniClueDescGroup = { link = "DiagnosticFloatingWarn" },
    MiniClueDescSingle = { link = "NormalFloat" },
    MiniClueNextKey = { link = "DiagnosticFloatingHint" },
    MiniClueNextKeyWithPostkeys = { link = "DiagnosticFloatingError" },
    MiniClueSeparator = { link = "DiagnosticFloatingInfo" },
    MiniClueTitle = { link = "FloatTitle" },
    MiniCompletionActiveParameter = { underline = true },
    MiniCursorword = { underline = true },
    MiniCursorwordCurrent = { underline = true },
    MiniDepsChangeAdded = { link = "FansiGreen" },
    MiniDepsChangeRemoved = { link = "FansiRed" },
    MiniDepsHint = { link = "DiagnosticHint" },
    MiniDepsInfo = { link = "DiagnosticInfo" },
    MiniDepsMsgBreaking = { link = "DiagnosticWarn" },
    MiniDepsPlaceholder = { link = "Comment" },
    MiniDepsTitle = { link = "Title" },
    MiniDepsTitleError = { link = "DiffDelete" },
    MiniDepsTitleSame = { link = "DiffChange" },
    MiniDepsTitleUpdate = { link = "DiffAdd" },
    MiniDiffOverAdd = { link = "DiffAdd" },
    MiniDiffOverChange = { link = "DiffText" },
    MiniDiffOverContext = { link = "DiffChange" },
    MiniDiffOverDelete = { link = "DiffDelete" },
    MiniDiffSignAdd = { link = "FansiGreen" },
    MiniDiffSignChange = { link = "FansiCyan" },
    MiniDiffSignDelete = { link = "FansiRed" },
    MiniFilesBorder = { link = "FloatBorder" },
    MiniFilesBorderModified = { link = "DiagnosticFloatingWarn" },
    MiniFilesCursorLine = { ctermbg = colors.bg2 },
    MiniFilesDirectory = { link = "Directory" },
    MiniFilesFile = { link = "FansiFg1" },
    MiniFilesNormal = { link = "NormalFloat" },
    MiniFilesTitle = { link = "FloatTitle" },
    MiniFilesTitleFocused = { link = "FansiOrangeBold" },
    MiniHipatternsFixme = { ctermfg = colors.bg0, ctermbg = colors.red, bold = config.bold },
    MiniHipatternsHack = { ctermfg = colors.bg0, ctermbg = colors.yellow, bold = config.bold },
    MiniHipatternsNote = { ctermfg = colors.bg0, ctermbg = colors.blue, bold = config.bold },
    MiniHipatternsTodo = { ctermfg = colors.bg0, ctermbg = colors.cyan, bold = config.bold },
    MiniIconsAzure = { link = "FansiBlue" },
    MiniIconsBlue = { link = "FansiBlue" },
    MiniIconsCyan = { link = "FansiCyan" },
    MiniIconsGreen = { link = "FansiGreen" },
    MiniIconsGrey = { link = "FansiFg0" },
    MiniIconsOrange = { link = "FansiOrange" },
    MiniIconsPurple = { link = "FansiMagenta" },
    MiniIconsRed = { link = "FansiRed" },
    MiniIconsYellow = { link = "FansiYellow" },
    MiniIndentscopeSymbol = { link = "FansiGray" },
    MiniIndentscopeSymbolOff = { link = "FansiYellow" },
    MiniJump = { link = "FansiOrangeUnderline" },
    MiniJump2dDim = { link = "FansiGray" },
    MiniJump2dSpot = { ctermfg = colors.orange, bold = config.bold, nocombine = true },
    MiniJump2dSpotAhead = { ctermfg = colors.cyan, ctermbg = colors.bg0, nocombine = true },
    MiniJump2dSpotUnique = { ctermfg = colors.yellow, bold = config.bold, nocombine = true },
    MiniMapNormal = { link = "NormalFloat" },
    MiniMapSymbolCount = { link = "Special" },
    MiniMapSymbolLine = { link = "Title" },
    MiniMapSymbolView = { link = "Delimiter" },
    MiniNotifyBorder = { link = "FloatBorder" },
    MiniNotifyNormal = { link = "NormalFloat" },
    MiniNotifyTitle = { link = "FloatTitle" },
    MiniOperatorsExchangeFrom = { link = "IncSearch" },
    MiniPickBorder = { link = "FloatBorder" },
    MiniPickBorderBusy = { link = "DiagnosticFloatingWarn" },
    MiniPickBorderText = { link = "FloatTitle" },
    MiniPickIconDirectory = { link = "Directory" },
    MiniPickIconFile = { link = "MiniPickNormal" },
    MiniPickHeader = { link = "DiagnosticFloatingHint" },
    MiniPickMatchCurrent = { ctermbg = colors.bg2 },
    MiniPickMatchMarked = { link = "Visual" },
    MiniPickMatchRanges = { link = "DiagnosticFloatingHint" },
    MiniPickNormal = { link = "NormalFloat" },
    MiniPickPreviewLine = { link = "CursorLine" },
    MiniPickPreviewRegion = { link = "IncSearch" },
    MiniPickPrompt = { link = "DiagnosticFloatingInfo" },
    MiniStarterCurrent = { nocombine = true },
    MiniStarterFooter = { link = "FansiGray" },
    MiniStarterHeader = { link = "Title" },
    MiniStarterInactive = { link = "Comment" },
    MiniStarterItem = { link = "Normal" },
    MiniStarterItemBullet = { link = "Delimiter" },
    MiniStarterItemPrefix = { link = "WarningMsg" },
    MiniStarterSection = { link = "Delimiter" },
    MiniStarterQuery = { link = "MoreMsg" },
    MiniStatuslineDevinfo = { link = "StatusLine" },
    MiniStatuslineFileinfo = { link = "StatusLine" },
    MiniStatuslineFilename = { link = "StatusLineNC" },
    MiniStatuslineInactive = { link = "StatusLineNC" },
    MiniStatuslineModeCommand = { ctermfg = colors.bg0, ctermbg = colors.green, bold = config.bold },
    MiniStatuslineModeInsert = { ctermfg = colors.bg0, ctermbg = colors.blue, bold = config.bold },
    MiniStatuslineModeNormal = { ctermfg = colors.bg0, ctermbg = colors.fg4, bold = config.bold },
    MiniStatuslineModeOther = { ctermfg = colors.bg0, ctermbg = colors.cyan, bold = config.bold },
    MiniStatuslineModeReplace = { ctermfg = colors.bg0, ctermbg = colors.red, bold = config.bold },
    MiniStatuslineModeVisual = { ctermfg = colors.bg0, ctermbg = colors.yellow, bold = config.bold },
    MiniSurround = { link = "IncSearch" },
    MiniTablineCurrent = {
      ctermfg = colors.green,
      ctermbg = colors.bg1,
      bold = config.bold,
      reverse = config.invert_tabline,
    },
    MiniTablineFill = { link = "TabLineFill" },
    MiniTablineHidden = { ctermfg = colors.bg4, ctermbg = colors.bg1, reverse = config.invert_tabline },
    MiniTablineModifiedCurrent = {
      ctermfg = colors.bg1,
      ctermbg = colors.green,
      bold = config.bold,
      reverse = config.invert_tabline,
    },
    MiniTablineModifiedHidden = { ctermfg = colors.bg1, ctermbg = colors.bg4, reverse = config.invert_tabline },
    MiniTablineModifiedVisible = { ctermfg = colors.bg1, ctermbg = colors.fg1, reverse = config.invert_tabline },
    MiniTablineTabpagesection = { link = "Search" },
    MiniTablineVisible = { ctermfg = colors.fg1, ctermbg = colors.bg1, reverse = config.invert_tabline },
    MiniTestEmphasis = { bold = config.bold },
    MiniTestFail = { link = "FansiRedBold" },
    MiniTestPass = { link = "FansiGreenBold" },
    MiniTrailspace = { ctermbg = colors.red },
    ["@comment"] = { link = "Comment" },
    ["@none"] = { ctermbg = "NONE", ctermfg = "NONE" },
    ["@preproc"] = { link = "PreProc" },
    ["@define"] = { link = "Define" },
    ["@operator"] = { link = "Operator" },
    ["@punctuation.delimiter"] = { link = "Delimiter" },
    ["@punctuation.bracket"] = { link = "Delimiter" },
    ["@punctuation.special"] = { link = "Delimiter" },
    ["@string"] = { link = "String" },
    ["@string.regex"] = { link = "String" },
    ["@string.regexp"] = { link = "String" },
    ["@string.escape"] = { link = "SpecialChar" },
    ["@string.special"] = { link = "SpecialChar" },
    ["@string.special.path"] = { link = "Underlined" },
    ["@string.special.symbol"] = { link = "Identifier" },
    ["@string.special.url"] = { link = "Underlined" },
    ["@character"] = { link = "Character" },
    ["@character.special"] = { link = "SpecialChar" },
    ["@boolean"] = { link = "Boolean" },
    ["@number"] = { link = "Number" },
    ["@number.float"] = { link = "Float" },
    ["@float"] = { link = "Float" },
    ["@function"] = { link = "Function" },
    ["@function.builtin"] = { link = "Special" },
    ["@function.call"] = { link = "Function" },
    ["@function.macro"] = { link = "Macro" },
    ["@function.method"] = { link = "Function" },
    ["@method"] = { link = "Function" },
    ["@method.call"] = { link = "Function" },
    ["@constructor"] = { link = "Special" },
    ["@parameter"] = { link = "Identifier" },
    ["@keyword"] = { link = "Keyword" },
    ["@keyword.conditional"] = { link = "Conditional" },
    ["@keyword.debug"] = { link = "Debug" },
    ["@keyword.directive"] = { link = "PreProc" },
    ["@keyword.directive.define"] = { link = "Define" },
    ["@keyword.exception"] = { link = "Exception" },
    ["@keyword.function"] = { link = "Keyword" },
    ["@keyword.import"] = { link = "Include" },
    ["@keyword.operator"] = { link = "FansiRed" },
    ["@keyword.repeat"] = { link = "Repeat" },
    ["@keyword.return"] = { link = "Keyword" },
    ["@keyword.storage"] = { link = "StorageClass" },
    ["@conditional"] = { link = "Conditional" },
    ["@repeat"] = { link = "Repeat" },
    ["@debug"] = { link = "Debug" },
    ["@label"] = { link = "Label" },
    ["@include"] = { link = "Include" },
    ["@exception"] = { link = "Exception" },
    ["@type"] = { link = "Type" },
    ["@type.builtin"] = { link = "Type" },
    ["@type.definition"] = { link = "Typedef" },
    ["@type.qualifier"] = { link = "Type" },
    ["@storageclass"] = { link = "StorageClass" },
    ["@attribute"] = { link = "PreProc" },
    ["@field"] = { link = "Identifier" },
    ["@property"] = { link = "Identifier" },
    ["@variable"] = { link = "FansiFg1" },
    ["@variable.builtin"] = { link = "Special" },
    ["@variable.member"] = { link = "Identifier" },
    ["@variable.parameter"] = { link = "Identifier" },
    ["@constant"] = { link = "Constant" },
    ["@constant.builtin"] = { link = "Special" },
    ["@constant.macro"] = { link = "Define" },
    ["@markup"] = { link = "FansiFg1" },
    ["@markup.strong"] = { bold = config.bold },
    ["@markup.italic"] = { link = "@text.emphasis" },
    ["@markup.underline"] = { underline = config.underline },
    ["@markup.strikethrough"] = { strikethrough = config.strikethrough },
    ["@markup.heading"] = { link = "Title" },
    ["@markup.raw"] = { link = "String" },
    ["@markup.math"] = { link = "Special" },
    ["@markup.environment"] = { link = "Macro" },
    ["@markup.environment.name"] = { link = "Type" },
    ["@markup.link"] = { link = "Underlined" },
    ["@markup.link.label"] = { link = "SpecialChar" },
    ["@markup.list"] = { link = "Delimiter" },
    ["@markup.list.checked"] = { link = "FansiGreen" },
    ["@markup.list.unchecked"] = { link = "FansiGray" },
    ["@comment.todo"] = { link = "Todo" },
    ["@comment.note"] = { link = "SpecialComment" },
    ["@comment.warning"] = { link = "WarningMsg" },
    ["@comment.error"] = { link = "ErrorMsg" },
    ["@diff.plus"] = { link = "diffAdded" },
    ["@diff.minus"] = { link = "diffRemoved" },
    ["@diff.delta"] = { link = "diffChanged" },
    ["@module"] = { link = "FansiFg1" },
    ["@namespace"] = { link = "FansiFg1" },
    ["@symbol"] = { link = "Identifier" },
    ["@text"] = { link = "FansiFg1" },
    ["@text.strong"] = { bold = config.bold },
    ["@text.emphasis"] = { italic = config.italic.emphasis },
    ["@text.underline"] = { underline = config.underline },
    ["@text.strike"] = { strikethrough = config.strikethrough },
    ["@text.title"] = { link = "Title" },
    ["@text.literal"] = { link = "String" },
    ["@text.uri"] = { link = "Underlined" },
    ["@text.math"] = { link = "Special" },
    ["@text.environment"] = { link = "Macro" },
    ["@text.environment.name"] = { link = "Type" },
    ["@text.reference"] = { link = "Constant" },
    ["@text.todo"] = { link = "Todo" },
    ["@text.todo.checked"] = { link = "FansiGreen" },
    ["@text.todo.unchecked"] = { link = "FansiGray" },
    ["@text.note"] = { link = "SpecialComment" },
    ["@text.note.comment"] = { ctermfg = colors.magenta, bold = config.bold },
    ["@text.warning"] = { link = "WarningMsg" },
    ["@text.danger"] = { link = "ErrorMsg" },
    ["@text.danger.comment"] = { ctermfg = colors.fg0, ctermbg = colors.red, bold = config.bold },
    ["@text.diff.add"] = { link = "diffAdded" },
    ["@text.diff.delete"] = { link = "diffRemoved" },
    ["@tag"] = { link = "Tag" },
    ["@tag.attribute"] = { link = "Identifier" },
    ["@tag.delimiter"] = { link = "Delimiter" },
    ["@punctuation"] = { link = "Delimiter" },
    ["@macro"] = { link = "Macro" },
    ["@structure"] = { link = "Structure" },
    ["@lsp.type.class"] = { link = "@type" },
    ["@lsp.type.comment"] = { link = "@comment" },
    ["@lsp.type.decorator"] = { link = "@macro" },
    ["@lsp.type.enum"] = { link = "@type" },
    ["@lsp.type.enumMember"] = { link = "@constant" },
    ["@lsp.type.function"] = { link = "@function" },
    ["@lsp.type.interface"] = { link = "@constructor" },
    ["@lsp.type.macro"] = { link = "@macro" },
    ["@lsp.type.method"] = { link = "@method" },
    ["@lsp.type.namespace"] = { link = "@namespace" },
    ["@lsp.type.parameter"] = { link = "@parameter" },
    ["@lsp.type.property"] = { link = "@property" },
    ["@lsp.type.struct"] = { link = "@type" },
    ["@lsp.type.type"] = { link = "@type" },
    ["@lsp.type.typeParameter"] = { link = "@type.definition" },
    ["@lsp.type.variable"] = { link = "@variable" },
  }

  for group, hl in pairs(config.overrides) do
    if groups[group] then
      -- "link" should not mix with other configs (:h hi-link)
      groups[group].link = nil
    end

    groups[group] = vim.tbl_extend("force", groups[group] or {}, hl)
  end

  return groups
end

---@param config FansiConfig?
Fansi.setup = function(config)
  Fansi.config = vim.tbl_deep_extend("force", Fansi.config, config or {})
end

--- main load function
Fansi.load = function()
  if vim.g.colors_name then
    vim.cmd.hi("clear")
  end
  vim.g.colors_name = "fansi"

  local groups = get_groups()

  -- add highlights
  for group, settings in pairs(groups) do
    -- if settings.sp == nil then
    vim.api.nvim_set_hl(0, group, settings)
    -- else
    --   vim.cmd("hi " .. group .. " guisp=" .. settings.sp .. " cterm=undercurl")
    -- end
  end
end

return Fansi
